repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: python -m pytest tests
        language: system
        types: [python]
        pass_filenames: false
        always_run: true