repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: python -m pytest tests
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.9
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.9
    hooks:
      # Compile requirements
      - id: pip-compile
        args: [ pyproject.toml, -o, requirements.txt ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.12
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format