[project]
name = "dynamicsystemabstraction"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pre-commit>=4.2.0",
    "pygame>=2.6.1",
    "pytest>=8.3.5",
]
