name: Build Simulation and Test
on:
  push:
    branches:
      - master

jobs:
  tests:
    name: Run All Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python
      run: uv python install

    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Run tests
      run: uv run pytest tests --junit-xml=pytest-results.xml

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results
        path: pytest-results.xml
        retention-days: 5

    - name: Print test summary
      if: always()
      run: uv run pytest tests --tb=short || true